"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[line_break]
disabled = false

[aws]
format = '[$symbol($profile )(\[$duration\] )]($style)'
symbol = " "
style = "bold yellow"

[nodejs]
format = "[$symbol($version )]($style)"

[python]
symbol = " "
style = "bold bright-blue"

[package]
disabled = true

# Add this to your starship.toml
[custom.detect_sensible_env]
command = ''' ~/.local/bin/detect-sensible-env.sh '''
when = '''[ -f ~/.local/bin/detect-sensible-env.sh ]  '''
style = 'bold red'
format = '[${output} ]($style)'
description = 'Show danger indication when a sensible environment variable is found.'
